### PR TITLE
Zoom at most to original image's size - Fix #60

### LINKED ISSUE #60: Zoom at most to original image's size
I'd like zoom to at most to the original image's size. It seems that the only way of doing that is with `customSize` or `data-zooming-width` / `data-zooming-height`, which requires knowing the image size. The two values also override the max scaling as well, meaning that I'd have to ajust those depending on the user's window size.

Any way an additional option could be added in for this use case?

### PR DESCRIPTION
**Pull request by migueldemoura**
**Not ready to merge.**

I've addressed both requirements at https://github.com/kingdido999/zooming/issues/60#issuecomment-372874260, let me know what you think. I also ran jpegoptim and removed some trailing spaces, hope that's ok.

As for the srcset issue, what do you think is the best course of action?

To Do:

- [x] Fix srcset messing up `.naturalWidth` and `.naturalHeight`.
- [x] Docs
- [ ] Tests

### CODE REVIEW

**Comment by migueldemoura** [comment]
I used `img.naturalHeight` and `img.naturalWidth` to get the max-res image's size. However, this method won't work with srcset as the returned values correspond to the currently selected srcset image.

With `window.innerWidth` = **400px**:

---

``` html
<img srcset="https://via.placeholder.com/280x280 280w,
             https://via.placeholder.com/440x440 440w,
             https://via.placeholder.com/800x800 800w"
     sizes="(max-width: 320px) 280px,
            (max-width: 480px) 440px,
            800px"
     src="https://via.placeholder.com/800x800"
>
```
**Natural Size: 440x440** (currently used image source)

---

``` html
<img src="https://via.placeholder.com/800x800">
```
**Natural Size: 800x800**

---

One way of fixing this issue if by moving the removal of srcset https://github.com/kingdido999/zooming/commit/717b997f89dca2156d1c4516183d86042886326f to before the calculation, so the returned values match the actual src size. This assuming that src always holds the max-res image, which isn't guaranteed.

That commit also forced the download of the src max-res image even if the zooming is made on small screens. That makes sense when grab is enabled, but may not be desirable when it's not (possible waste of bandwidth if that image is the max-res one).

Thoughts? :smile:

**Comment by kingdido999** [comment]
Both approaches seem doable to me, you can make the call 👍

**Comment by migueldemoura** [comment]
I'm going with the `Image.load()` approach. Just took a look at this and implemented a solution. Just one question, why is `target` reset on each `zooming.open` (https://github.com/kingdido999/zooming/blob/master/src/modules/zooming.js#L98)?

**Comment by kingdido999** [comment]
Because target image might be different each time it zooms in, so we need to initialize `target` element correctly.

**Comment by migueldemoura** [comment]
I'm saving **`srcOriginalSize`** `{width: naturalWidth, height: naturalHeight}` as a `target` prop, and all props are reset on each `zooming.open` due to `target.init`.

Since there's an image preload at zooming's constructor and I'm saving the size at `target`, I'd need a new control structure to maintain the state. A simple way to do this is by always executing the new Image call at `zooming.open`; caching should mitigate the network overhead, although it isn't a solution I'm happy with.

I've pushed that option, let me know what you think.

**Comment by migueldemoura** [comment]
If `preloadImage` is `false`, the zoom animation is only triggered after the image is loaded, as you said. I just checked another script (fluidbox) that does something similar and they have this exact issue - there's a significant interaction delay in poor network conditions. Even if we did execute the animation before the loading is finished and then ajusted to the actual image size, it would still be poor UX.
Forcing a preload isn't a solution since the problem we have is with "responsive" images - preloading the high-res version would defeat the purpose.

As for your proposal, reverting the last commit should satisfy those requirements, right?
The issue with `naturalWidth` and `naturalHeight` is that the user will expect `customSize: 100%` to apply to the `srcOriginal`, and not to the thumbnail or small image. I think the best approach would be to use the `natural` methods but allow the user to overide them with, for example, `data-zooming-width/heigth`.

In essence:
- Revert to the previous commit that uses `naturalWidth` and `naturalHeight`.
- If the user provides `data-zooming-width` and `data-zooming-heigth`, use them instead of the `natural` values.

**Comment by kingdido999** [comment]
The zoom animation should be instant and that's why `loadImage` and zoom in action happens in parallel in the original code. And to avoid performance issues on a page with tons of images with hi-res sources, I made `preloadImage` to false by default.

I completely agree with your thoughts and approach. Please go ahead.

**Comment by kingdido999** [comment]
And turns out your initial thought of using ad-hoc data attributes is indeed the correct way to do it :)

**Comment by migueldemoura** [comment]
I'd much rather have zooming get the image size transparently, but the UX tradeoff is too big.

Just pushed new changes. Sounds good?
I need some help with the tests though.

**Comment by kingdido999** [comment]
I'm going to be pretty busy this weekend, so if you don't get a chance to write docs and tests, I'll try to do those next week (btw the current tests we have are very basic and kinda messy). But do let me know if you have any questions.

**Comment by migueldemoura** [comment]
Was on the same boat.

Thanks for changing branch, completely missed that. As for the docs and tests, did you start writing them?

**Comment by kingdido999** [comment]
Not yet. Maybe tomorrow I'll have some time, but feel free to work on it if you have time 😄

**Comment by kingdido999** [comment]
Updated doc in this commit: 4d88ca4075d22bc4af6efe1842003d320198f013

**Comment by migueldemoura** [comment]
Updated the inline doc for the customSize option inside `options.js`. How would you like to proceed with tests? Can I help?

**Comment by kingdido999** [comment]
Cool! I'll merge it to the feature branch now and do some manual testing to make sure it works fine.

**Pull request merged**
