### PR TITLE
more medium

### PR DESCRIPTION
**Pull request by liximomo**
* rename bgOpacity to overlay just because data-overlay is looking better. 😃 
* offer config override at image level.
* customizable scale window based on data-width and data-height.
* fix scrollbar blinking when appending image to body in open method.

sorry for my bad english 😞

### CODE REVIEW

**Comment by kingdido999** [comment]
@liximomo Thanks for the PR. Here are my thoughts:

- I don't like `overlay` over `bgOpactiy`, they are different things and the latter is more appropriate.
- Being able to config each image individually is a great idea. If we decide to implement this, probably it should be done at API level, i.e., support multiple API instances, rather than override individual images. We can use data-attribute as an additional way to config options.
- What is the use case of customizing window width and height?
- What OS and browser are having this scrollbar blinking issue?

Btw, it's better to include only one change per PR as it makes things easier. Also, you might want to discuss with me (create an issue) before making any significant change so we are on the same page.

Let me know what you think :)

**Comment by liximomo** [comment]
@kingdido999 
* What is the use case of customizing window width and height?
  Because medium has it. And I don't want every image to scale to fit window. I guess medius guys also think so as well.

**Comment by liximomo** [comment]
* What is the use case of customizing window width and height?
  Because medium has it. And I don't want every image to scale to fit window. I guess medius guys    also think so as well.
* What OS and browser are having this scrollbar blinking issue?
  Chrome. The demo page could reproduces it. The `position: absolute` could expand body height, so the add and remove operation results a scrollbar blinking.

**Comment by liximomo** [comment]
I have used zooming on my blog. I need  config each image individually. So I modify the code. I want keep using  zooming, so I send the PR. It's so nice to make my blog have an medium experience. Thanks your job.

**Comment by kingdido999** [comment]
@liximomo Instead of customizing window width and height, why not set `scaleBase` to less than 1? I understand that you want to configure individual images, as I said, I'll see what I can do to support multiple API instances.

**Comment by liximomo** [comment]
Because I want to image to scale to it's origin height and width. Say my web site content width is 400px. Every image will be full width which is 400px no matter what dimension it is. I only want these images to zoom to the origin dimension. The scaleBase will make them all the same. An 500 x 500 image would look less nice than a 800 x 800 one when they scale to window with initially show in an 400 x 400 dimension.

**Comment by kingdido999** [comment]
@liximomo Understood. I'm considering adding a boolean option so you can preserve the image original height and width after zoomed in. Btw, the latest code supports multiple instances, each can be configured individually. Also fixed the scrollbar blinking issue.

**Comment by kingdido999** [comment]
@liximomo Now you can customize the width and height of an image after zoomed in using option `customSize`. See #17.

**Pull request closed without merging**
