### PR TITLE
Use the latest Rollup API #50 and build final modules (es, umd)

### PR DESCRIPTION
**Pull request by mahish**
The test was passed with success. I also tested it on my own project and it worked fine. However you better look at it. This is my first PR ever:)

### CODE REVIEW

**Comment by kingdido999** [comment]
Looks good to me！Let me try it out later today. Does the new script also generate the minified bundle as well? I used to include the uglify plugin.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mahish** [comment]
Nope. I removed it. I thought it is not necessary since I minify the bundle on the level of my web project (as everyone does?). No problem to add it back tho..

I also removed:
- `rollup-watch` (deprecated). The watch method is part of the rollup now. 
- `transform-object-assign` from babel plugins. It works without it. However, i searched little bit more about the package and the reason why you had it there (`Object.assign`) which is now present even in the bundle. Is it because of support for IE11?

**Comment by kingdido999** [comment]
I still think we should minify the bundle for people who use this library without a module loader. It seems to me rollup config file can't generate multiple outputs based on different plugins, so we may have to use Rollup API to generate both bundles at the same time, like what I originally did in the script. Do you mind working on it?

**Comment by mahish** [comment]
You can have two different configs. This has been taken from their doc page:

´rollup --config rollup.config.dev.js ´
´rollup --config rollup.config.prod.js ´

**Comment by kingdido999** [comment]
Yes, I like this approach a lot!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
